2019-09-21 20:24:33.721 [error] <0.445.0>@Elixir.LarsonWeb.Rabbit:call:16 gen_server <0.445.0> terminated with reason: no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16
2019-09-21 20:24:33.776 [error] <0.445.0>@Elixir.LarsonWeb.Rabbit:call:16 CRASH REPORT Process <0.445.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16
2019-09-21 20:24:33.776 [error] <0.324.0>@Elixir.LarsonWeb.Rabbit:call:16 Supervisor {<0.324.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.445.0> exit with reason no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16 in context child_terminated
2019-09-21 20:24:37.847 [error] <0.452.0>@Elixir.LarsonWeb.Rabbit:call:16 gen_server <0.452.0> terminated with reason: no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16
2019-09-21 20:24:37.848 [error] <0.452.0>@Elixir.LarsonWeb.Rabbit:call:16 CRASH REPORT Process <0.452.0> with 0 neighbours crashed with reason: no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16
2019-09-21 20:24:37.848 [error] <0.318.0>@Elixir.LarsonWeb.Rabbit:call:16 Supervisor {<0.318.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.452.0> exit with reason no match of right hand value {error,econnrefused} in 'Elixir.LarsonWeb.Rabbit':call/1 line 16 in context child_terminated
2019-09-21 21:53:54.631 [error] <0.428.0> ** Task <0.428.0> terminating
** Started from 'Elixir.LarsonWeb.Endpoint'
** When function  == fun Elixir.Phoenix.Endpoint.Watcher:watch/3
**      arguments == [<<"node">>,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],[{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]]
** Reason for termination == 
** {watcher_command_error,[{'Elixir.Phoenix.Endpoint.Watcher',watch,3,[{file,"lib/phoenix/endpoint/watcher.ex"},{line,29}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-21 21:53:54.638 [error] <0.428.0> CRASH REPORT Process <0.428.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 29
2019-09-21 21:53:54.638 [error] <0.297.0> Supervisor 'Elixir.LarsonWeb.Endpoint' had child {node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,
       <<"development">>,<<"--watch-stdin">>,
       {cd,<<"/home/abruxelle/phoenix/larson/assets">>}]} started with 'Elixir.Phoenix.Endpoint.Watcher':start_link(node, [<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>], [{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]) at <0.428.0> exit with reason watcher_command_error in context child_terminated
2019-09-21 21:53:57.414 [error] <0.560.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.560.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:53:57.444 [error] <0.560.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.560.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:53:57.444 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.560.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:53:58.451 [error] <0.565.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.565.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:53:58.452 [error] <0.565.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.565.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:53:58.452 [error] <0.321.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.565.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:54:00.456 [error] <0.566.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.566.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:00.458 [error] <0.566.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.566.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:00.458 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.566.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:54:08.978 [error] <0.436.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.436.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:08.992 [error] <0.436.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.436.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:08.992 [error] <0.322.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.322.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.436.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:54:10.071 [error] <0.443.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.443.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:10.072 [error] <0.443.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.443.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:10.072 [error] <0.323.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.323.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.443.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:54:10.362 [error] <0.456.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.456.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:10.362 [error] <0.456.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.456.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:54:10.362 [error] <0.318.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.318.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.456.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:55:06.509 [error] <0.437.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.437.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:55:06.509 [error] <0.437.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.437.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:55:06.510 [error] <0.321.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.437.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 21:55:07.266 [error] <0.444.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.444.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:55:07.267 [error] <0.444.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.444.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 21:55:07.267 [error] <0.318.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.318.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.444.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:01:14.890 [error] <0.428.0> ** Task <0.428.0> terminating
** Started from 'Elixir.LarsonWeb.Endpoint'
** When function  == fun Elixir.Phoenix.Endpoint.Watcher:watch/3
**      arguments == [<<"node">>,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],[{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]]
** Reason for termination == 
** {watcher_command_error,[{'Elixir.Phoenix.Endpoint.Watcher',watch,3,[{file,"lib/phoenix/endpoint/watcher.ex"},{line,29}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-21 22:01:14.902 [error] <0.428.0> CRASH REPORT Process <0.428.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 29
2019-09-21 22:01:14.903 [error] <0.297.0> Supervisor 'Elixir.LarsonWeb.Endpoint' had child {node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,
       <<"development">>,<<"--watch-stdin">>,
       {cd,<<"/home/abruxelle/phoenix/larson/assets">>}]} started with 'Elixir.Phoenix.Endpoint.Watcher':start_link(node, [<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>], [{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]) at <0.428.0> exit with reason watcher_command_error in context child_terminated
2019-09-21 22:05:09.442 [error] <0.428.0> ** Task <0.428.0> terminating
** Started from 'Elixir.LarsonWeb.Endpoint'
** When function  == fun Elixir.Phoenix.Endpoint.Watcher:watch/3
**      arguments == [<<"node">>,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],[{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]]
** Reason for termination == 
** {watcher_command_error,[{'Elixir.Phoenix.Endpoint.Watcher',watch,3,[{file,"lib/phoenix/endpoint/watcher.ex"},{line,29}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-21 22:05:09.453 [error] <0.428.0> CRASH REPORT Process <0.428.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 29
2019-09-21 22:05:09.454 [error] <0.297.0> Supervisor 'Elixir.LarsonWeb.Endpoint' had child {node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,
       <<"development">>,<<"--watch-stdin">>,
       {cd,<<"/home/abruxelle/phoenix/larson/assets">>}]} started with 'Elixir.Phoenix.Endpoint.Watcher':start_link(node, [<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>], [{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]) at <0.428.0> exit with reason watcher_command_error in context child_terminated
2019-09-21 22:05:11.894 [error] <0.718.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.718.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:11.903 [error] <0.718.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.718.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:11.904 [error] <0.324.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.324.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.718.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:12.922 [error] <0.724.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.724.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:12.923 [error] <0.724.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.724.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:12.924 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.724.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:14.927 [error] <0.725.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.725.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:14.928 [error] <0.725.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.725.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:14.929 [error] <0.321.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.725.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:19.932 [error] <0.726.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.726.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:19.935 [error] <0.726.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.726.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:19.936 [error] <0.319.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.319.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.726.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:29.939 [error] <0.728.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.728.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:29.939 [error] <0.728.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.728.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:29.939 [error] <0.319.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.319.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.728.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:41.860 [error] <0.437.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.437.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:41.861 [error] <0.437.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.437.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:41.862 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.437.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:42.858 [error] <0.456.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.456.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:42.860 [error] <0.456.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.456.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:42.861 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.456.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:43.989 [error] <0.462.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.462.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:43.991 [error] <0.462.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.462.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:43.991 [error] <0.323.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.323.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.462.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:45.995 [error] <0.463.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.463.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:45.996 [error] <0.463.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.463.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:45.997 [error] <0.319.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.319.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.463.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:50.623 [error] <0.479.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.479.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:50.624 [error] <0.479.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.479.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:50.624 [error] <0.319.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.319.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.479.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:51.636 [error] <0.485.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.485.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:51.637 [error] <0.485.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.485.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:51.637 [error] <0.320.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.320.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.485.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:53.639 [error] <0.486.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.486.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:53.641 [error] <0.486.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.486.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:53.641 [error] <0.321.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.486.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:05:58.644 [error] <0.487.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.487.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:58.645 [error] <0.487.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.487.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:05:58.645 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.487.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:08.647 [error] <0.488.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.488.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:08.649 [error] <0.488.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.488.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:08.649 [error] <0.321.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.321.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.488.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:18.652 [error] <0.489.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.489.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:18.653 [error] <0.489.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.489.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:18.653 [error] <0.323.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.323.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.489.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:28.655 [error] <0.490.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.490.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:28.655 [error] <0.490.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.490.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:28.656 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.490.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:38.954 [error] <0.510.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.510.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:38.955 [error] <0.510.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.510.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:38.955 [error] <0.320.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.320.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.510.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:40.011 [error] <0.515.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.515.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:40.012 [error] <0.515.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.515.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:40.013 [error] <0.318.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.318.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.515.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:42.015 [error] <0.516.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.516.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:42.016 [error] <0.516.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.516.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:42.017 [error] <0.317.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.317.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.516.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:06:47.020 [error] <0.517.0>@Elixir.LarsonWeb.ScoreChannel:join:4 gen_server <0.517.0> terminated with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:47.021 [error] <0.517.0>@Elixir.LarsonWeb.ScoreChannel:join:4 CRASH REPORT Process <0.517.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4
2019-09-21 22:06:47.022 [error] <0.318.0>@Elixir.LarsonWeb.ScoreChannel:join:4 Supervisor {<0.318.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.517.0> exit with reason no function clause matching 'Elixir.LarsonWeb.ScoreChannel':join(<<"score:main">>, #{}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.LarsonWeb.ScoreChannel',...}) line 4 in context child_terminated
2019-09-21 22:08:51.982 [error] <0.428.0> ** Task <0.428.0> terminating
** Started from 'Elixir.LarsonWeb.Endpoint'
** When function  == fun Elixir.Phoenix.Endpoint.Watcher:watch/3
**      arguments == [<<"node">>,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],[{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]]
** Reason for termination == 
** {watcher_command_error,[{'Elixir.Phoenix.Endpoint.Watcher',watch,3,[{file,"lib/phoenix/endpoint/watcher.ex"},{line,29}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-21 22:08:51.984 [error] <0.428.0> CRASH REPORT Process <0.428.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 29
2019-09-21 22:08:51.984 [error] <0.297.0> Supervisor 'Elixir.LarsonWeb.Endpoint' had child {node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,
       <<"development">>,<<"--watch-stdin">>,
       {cd,<<"/home/abruxelle/phoenix/larson/assets">>}]} started with 'Elixir.Phoenix.Endpoint.Watcher':start_link(node, [<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>], [{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]) at <0.428.0> exit with reason watcher_command_error in context child_terminated
2019-09-21 22:12:44.059 [error] <0.624.0> ** Task <0.624.0> terminating
** Started from 'Elixir.LarsonWeb.Endpoint'
** When function  == fun Elixir.Phoenix.Endpoint.Watcher:watch/3
**      arguments == [<<"node">>,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],[{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]]
** Reason for termination == 
** {watcher_command_error,[{'Elixir.Phoenix.Endpoint.Watcher',watch,3,[{file,"lib/phoenix/endpoint/watcher.ex"},{line,29}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-21 22:12:44.059 [error] <0.624.0> CRASH REPORT Process <0.624.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 29
2019-09-21 22:12:44.059 [error] <0.297.0> Supervisor 'Elixir.LarsonWeb.Endpoint' had child {node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,
       <<"development">>,<<"--watch-stdin">>,
       {cd,<<"/home/abruxelle/phoenix/larson/assets">>}]} started with 'Elixir.Phoenix.Endpoint.Watcher':start_link(node, [<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>], [{cd,<<"/home/abruxelle/phoenix/larson/assets">>}]) at <0.624.0> exit with reason watcher_command_error in context child_terminated
